baseurl = "http://dso-studio.teachera.io/"
languageCode = "en-us"
title = "DevSecOps Studio"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Mohammed A.Imran"
	description = "Virtual environment for learning DevSecOps"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/teacheraio/DevSecOps-Studio"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "red"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "secfigo"
	github  = "raseyon"
	email   = "info [at] teachera.io"


[[menu.main]]
	name   = "DevSecOps Studio"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Getting started"
	url    = "/getting-started/"
	weight = 20

[[menu.main]]
	name   = "Tools Used"
	url    = "/tools/"
	weight = 30
    
[[menu.main]]
	name   = "Roadmap & Changelog"
	url    = "/roadmap/"
	weight = 40

[[menu.main]]
	name   = "License"
	url    = "/license/"
	weight = 50


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
